// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_code_ from "./routes/[code].ts";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_r from "./routes/api/r.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $use from "./routes/use.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Map from "./islands/Map.tsx";
import * as $Toast from "./islands/Toast.js";
import * as $Tokutei from "./islands/Tokutei.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[code].ts": $_code_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/r.ts": $api_r,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/use.tsx": $use,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Map.tsx": $Map,
    "./islands/Toast.js": $Toast,
    "./islands/Tokutei.tsx": $Tokutei,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
